# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 11:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0002_basecustomuser_middle_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='basecustomuser',
            name='gender',
            field=models.CharField(choices=[('male', 'Мужской'), ('female', 'Женский')], default='male', max_length=6, verbose_name='gender'),
        ),
    ]
