# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 11:22
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0003_basecustomuser_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='basecustomuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=16, validators=[django.core.validators.RegexValidator('^((8|\\+7)[\\- ]?)?(\\(?\\d{3}\\)?[\\- ]?)?[\\d\\- ]{7,10}$')], verbose_name='phone number'),
        ),
    ]
