# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 11:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0004_basecustomuser_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='basecustomuser',
            name='birthday',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 24, 11, 25, 10, 855470, tzinfo=utc), verbose_name='birthday'),
        ),
    ]
