# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 11:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0005_basecustomuser_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basecustomuser',
            name='birthday',
            field=models.DateTimeField(default='timezone.now()', verbose_name='birthday'),
        ),
    ]
