# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 11:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0006_auto_20170424_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='basecustomuser',
            name='address',
            field=models.CharField(blank=True, max_length=100, verbose_name='address'),
        ),
    ]
