# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 08:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0007_basecustomuser_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basecustomuser',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterField(
            model_name='basecustomuser',
            name='birthday',
            field=models.DateField(verbose_name='birthday'),
        ),
    ]
